"use strict";
let products = [
    {
        id:1,
        title:"Hooded Item",
        name:"Basic Casual Hoodie For Men's XL",
        imageUrl:"images/product_1.png",
        qty:1,
        newPrice:"$610.00",
        category:"MEN'S",
        offre:"NEW",
        size:"large",
        desc:"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed non risus. Suspendisse lectus.",
    },
    {
        id:2,
        title:"Tote Bag Item",
        name:"Organic Heavy Duty Cotton Tote Bag",
        imageUrl:"images/product_2.png",
        qty:1,
        oldPrice:"$590.00",
        newPrice:"$610.00",
        category:"WOMEN'S",
        offre:"-$20",  
        size:"medium",
        desc:"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed non risus. Suspendisse lectus.",
    },
    {
        id:3,
        title:"Uniqlo Long Sleeve",
        name:"Uniqlo Women's Long Sleeve (UNIQLO AU)",
        imageUrl:"images/product_3.png",
        qty:1,
        newPrice:"$120.00",
        category:"WOMEN'S",
        offre:"NEW",  
        size:"small",
        desc:"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed non risus. Suspendisse lectus.",
    },
    {
        id:4,
        title:"Sport Handbag",
        name:"Shopee Sport Handbag Pouch bag For Men",
        imageUrl:"images/product_4.png",
        qty:1,
        oldPrice:"$450.00",
        newPrice:"$410.00",
        category:"ACCESSORIES",
        offre:"-$40",  
        size:"small",
        desc:"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed non risus. Suspendisse lectus.",
    },
    {
        id:5,
        title:"Sport Shoes",
        name:"Womens Trainers And Sport Pumps",
        imageUrl:"images/product_5.png",
        qty:1,
        newPrice:"$180.00",
        category:"WOMEN'S",
        offre:"NEW",  
        size:"large",
        desc:"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed non risus. Suspendisse lectus.",
    },
    {
        id:6,
        title:"Rayben Sunglasses",
        name:"Ray Ban RB30ASX25JM Aviator Sunglasses",
        imageUrl:"images/product_6.png",
        qty:1,
        oldPrice:"$290.00",
        newPrice:"$200.00",
        category:"ACCESSORIES",
        offre:"-$90",  
        size:"large",
        desc:"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed non risus. Suspendisse lectus.",
    },
    {
        id:7,
        title:"Seamless Long Sleeve",
        name:"Women's Seamless Long Sleeve T-Shirt",
        imageUrl:"images/product_7.png",
        qty:1,
        newPrice:"$240.00",
        category:"WOMEN'S",
        offre:"NEW", 
        size:"medium",
        desc:"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed non risus. Suspendisse lectus.",
    },
    {
        id:8,
        title:"Leather Wallet",
        name:"Leather Wallet With Double Zippers",
        imageUrl:"images/product_8.png",
        qty:1,
        oldPrice:"$70.00",
        newPrice:"$50.00",
        category:"ACCESSORIES",
        offre:"-$20",  
        size:"medium",
        desc:"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed non risus. Suspendisse lectus.",
    },
    {
        id:9,
        title:"Neck Long Sleeve",
        name:"Airism Protection Crew Neck Long Sleeve",
        imageUrl:"images/product_9.png",
        qty:1,
        newPrice:"$520.00",
        category:"MEN'S",
        offre:"NEW",  
        size:"large",
        desc:"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed non risus. Suspendisse lectus.",
    },
    {
        id:10,
        title:"Yoke Long Sleeve",
        name:"Contrast Back Yoke Full Sleeves T-Shirt",
        imageUrl:"images/product_10.png",
        qty:1,
        oldPrice:"$490.00",
        newPrice:"$430.00",
        category:"MEN'S",
        offre:"-$60",
        size:"medium",
        desc:"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed non risus. Suspendisse lectus.",
    },
]